export const graphData = {
  nodes: [
    // Group 1: nodes 1-33
    { id: "1", title: "Node 1", value: 1, type: "department", group: 1 },
    { id: "2", title: "Node 2", value: 2, type: "fruit", group: 1 },
    { id: "3", title: "Node 3", value: 3, type: "3c", group: 1 },
    { id: "4", title: "Node 4", value: 4, type: "sports", group: 1 },
    { id: "5", title: "Node 5", value: 5, type: "windows", group: 1 },
    { id: "6", title: "Node 6", value: 6, type: "apple", group: 1 },
    { id: "7", title: "Node 7", value: 7, type: "coffee", group: 1 },
    { id: "8", title: "Node 8", value: 8, type: "orange", group: 1 },
    { id: "9", title: "Node 9", value: 9, type: "banana", group: 1 },
    { id: "10", title: "Node 10", value: 1, type: "department", group: 1 },
    { id: "11", title: "Node 11", value: 1, type: "fruit", group: 1 },
    { id: "12", title: "Node 12", value: 2, type: "3c", group: 1 },
    { id: "13", title: "Node 13", value: 3, type: "sports", group: 1 },
    { id: "14", title: "Node 14", value: 4, type: "windows", group: 1 },
    { id: "15", title: "Node 15", value: 5, type: "apple", group: 1 },
    { id: "16", title: "Node 16", value: 6, type: "coffee", group: 1 },
    { id: "17", title: "Node 17", value: 7, type: "orange", group: 1 },
    { id: "18", title: "Node 18", value: 8, type: "banana", group: 1 },
    { id: "19", title: "Node 19", value: 9, type: "department", group: 1 },
    { id: "20", title: "Node 20", value: 1, type: "fruit", group: 1 },
    { id: "21", title: "Node 21", value: 2, type: "3c", group: 1 },
    { id: "22", title: "Node 22", value: 2, type: "sports", group: 1 },
    { id: "23", title: "Node 23", value: 2, type: "windows", group: 1 },
    { id: "24", title: "Node 24", value: 4, type: "apple", group: 1 },
    { id: "25", title: "Node 25", value: 5, type: "coffee", group: 1 },
    { id: "26", title: "Node 26", value: 6, type: "orange", group: 1 },
    { id: "27", title: "Node 27", value: 7, type: "banana", group: 1 },
    { id: "28", title: "Node 28", value: 8, type: "department", group: 1 },
    { id: "29", title: "Node 29", value: 9, type: "fruit", group: 1 },
    { id: "30", title: "Node 30", value: 1, type: "3c", group: 1 },
    { id: "31", title: "Node 31", value: 3, type: "sports", group: 1 },
    { id: "32", title: "Node 32", value: 3, type: "windows", group: 1 },
    { id: "33", title: "Node 33", value: 3, type: "apple", group: 1 },

    // Group 2: nodes 34-66
    { id: "34", title: "Node 34", value: 3, type: "coffee", group: 2 },
    { id: "35", title: "Node 35", value: 5, type: "orange", group: 2 },
    { id: "36", title: "Node 36", value: 6, type: "banana", group: 2 },
    { id: "37", title: "Node 37", value: 7, type: "department", group: 2 },
    { id: "38", title: "Node 38", value: 8, type: "fruit", group: 2 },
    { id: "39", title: "Node 39", value: 9, type: "3c", group: 2 },
    { id: "40", title: "Node 40", value: 0, type: "sports", group: 2 },
    { id: "41", title: "Node 41", value: 1, type: "windows", group: 2 },
    { id: "42", title: "Node 42", value: 2, type: "apple", group: 2 },
    { id: "43", title: "Node 43", value: 3, type: "coffee", group: 2 },
    { id: "44", title: "Node 44", value: 4, type: "orange", group: 2 },
    { id: "45", title: "Node 45", value: 5, type: "banana", group: 2 },
    { id: "46", title: "Node 46", value: 6, type: "department", group: 2 },
    { id: "47", title: "Node 47", value: 7, type: "fruit", group: 2 },
    { id: "48", title: "Node 48", value: 8, type: "3c", group: 2 },
    { id: "49", title: "Node 49", value: 9, type: "sports", group: 2 },
    { id: "50", title: "Node 50", value: 0, type: "windows", group: 2 },
    { id: "51", title: "Node 51", value: 1, type: "apple", group: 2 },
    { id: "52", title: "Node 52", value: 2, type: "coffee", group: 2 },
    { id: "53", title: "Node 53", value: 3, type: "orange", group: 2 },
    { id: "54", title: "Node 54", value: 4, type: "banana", group: 2 },
    { id: "55", title: "Node 55", value: 5, type: "department", group: 2 },
    { id: "56", title: "Node 56", value: 6, type: "fruit", group: 2 },
    { id: "57", title: "Node 57", value: 7, type: "3c", group: 2 },
    { id: "58", title: "Node 58", value: 8, type: "sports", group: 2 },
    { id: "59", title: "Node 59", value: 9, type: "windows", group: 2 },
    { id: "60", title: "Node 60", value: 0, type: "apple", group: 2 },
    { id: "61", title: "Node 61", value: 1, type: "coffee", group: 2 },
    { id: "62", title: "Node 62", value: 2, type: "orange", group: 2 },
    { id: "63", title: "Node 63", value: 3, type: "banana", group: 2 },
    { id: "64", title: "Node 64", value: 4, type: "department", group: 2 },
    { id: "65", title: "Node 65", value: 5, type: "fruit", group: 2 },
    { id: "66", title: "Node 66", value: 6, type: "3c", group: 2 },

    // Group 3: nodes 67-100
    { id: "67", title: "Node 67", value: 7, type: "sports", group: 3 },
    { id: "68", title: "Node 68", value: 8, type: "windows", group: 3 },
    { id: "69", title: "Node 69", value: 9, type: "apple", group: 3 },
    { id: "70", title: "Node 70", value: 0, type: "coffee", group: 3 },
    { id: "71", title: "Node 71", value: 1, type: "orange", group: 3 },
    { id: "72", title: "Node 72", value: 2, type: "banana", group: 3 },
    { id: "73", title: "Node 73", value: 3, type: "department", group: 3 },
    { id: "74", title: "Node 74", value: 4, type: "fruit", group: 3 },
    { id: "75", title: "Node 75", value: 5, type: "3c", group: 3 },
    { id: "76", title: "Node 76", value: 6, type: "sports", group: 3 },
    { id: "77", title: "Node 77", value: 7, type: "windows", group: 3 },
    { id: "78", title: "Node 78", value: 8, type: "apple", group: 3 },
    { id: "79", title: "Node 79", value: 9, type: "coffee", group: 3 },
    { id: "80", title: "Node 80", value: 0, type: "orange", group: 3 },
    { id: "81", title: "Node 81", value: 1, type: "banana", group: 3 },
    { id: "82", title: "Node 82", value: 2, type: "department", group: 3 },
    { id: "83", title: "Node 83", value: 3, type: "fruit", group: 3 },
    { id: "84", title: "Node 84", value: 4, type: "3c", group: 3 },
    { id: "85", title: "Node 85", value: 5, type: "sports", group: 3 },
    { id: "86", title: "Node 86", value: 6, type: "windows", group: 3 },
    { id: "87", title: "Node 87", value: 7, type: "apple", group: 3 },
    { id: "88", title: "Node 88", value: 8, type: "coffee", group: 3 },
    { id: "89", title: "Node 89", value: 9, type: "orange", group: 3 },
    { id: "90", title: "Node 90", value: 0, type: "banana", group: 3 },
    { id: "91", title: "Node 91", value: 1, type: "department", group: 3 },
    { id: "92", title: "Node 92", value: 2, type: "fruit", group: 3 },
    { id: "93", title: "Node 93", value: 3, type: "3c", group: 3 },
    { id: "94", title: "Node 94", value: 4, type: "sports", group: 3 },
    { id: "95", title: "Node 95", value: 5, type: "windows", group: 3 },
    { id: "96", title: "Node 96", value: 6, type: "apple", group: 3 },
    { id: "97", title: "Node 97", value: 7, type: "coffee", group: 3 },
    { id: "98", title: "Node 98", value: 8, type: "orange", group: 3 },
    { id: "99", title: "Node 99", value: 9, type: "banana", group: 3 },
    { id: "100", title: "Node 100", value: 1, type: "department", group: 3 },
  ],
  links: [
    // GROUP 1 LINKS - Ring/Circle structure for Group 1
    {
      source: "1",
      target: "2",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "2",
      target: "3",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "3",
      target: "4",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "4",
      target: "5",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "5",
      target: "6",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "6",
      target: "7",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "7",
      target: "8",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "8",
      target: "9",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "9",
      target: "10",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "10",
      target: "11",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "11",
      target: "12",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "12",
      target: "13",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "13",
      target: "14",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "14",
      target: "15",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "15",
      target: "16",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "16",
      target: "17",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "17",
      target: "18",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "18",
      target: "19",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "19",
      target: "20",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "20",
      target: "21",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "21",
      target: "22",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "22",
      target: "23",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "23",
      target: "24",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "24",
      target: "25",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "25",
      target: "26",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "26",
      target: "27",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "27",
      target: "28",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "28",
      target: "29",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "29",
      target: "30",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "30",
      target: "31",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "31",
      target: "32",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "32",
      target: "33",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },
    {
      source: "33",
      target: "1",
      value: 30,
      description: "Group 1 Ring",
      group: 1,
    },

    // Additional connections within Group 1 - Star structure with node 15 as center
    {
      source: "15",
      target: "1",
      value: 25,
      description: "Group 1 Star",
      group: 1,
    },
    {
      source: "15",
      target: "5",
      value: 25,
      description: "Group 1 Star",
      group: 1,
    },
    {
      source: "15",
      target: "10",
      value: 25,
      description: "Group 1 Star",
      group: 1,
    },
    {
      source: "15",
      target: "20",
      value: 25,
      description: "Group 1 Star",
      group: 1,
    },
    {
      source: "15",
      target: "25",
      value: 25,
      description: "Group 1 Star",
      group: 1,
    },
    {
      source: "15",
      target: "30",
      value: 25,
      description: "Group 1 Star",
      group: 1,
    },

    // GROUP 2 LINKS - Star structure for Group 2 with node 50 as center
    {
      source: "50",
      target: "34",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "35",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "36",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "37",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "38",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "39",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "40",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "41",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "42",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "43",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "44",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "45",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "46",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "47",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "48",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "49",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "51",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "52",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "53",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "54",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "55",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "56",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "57",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "58",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "59",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "60",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "61",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "62",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "63",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "64",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "65",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },
    {
      source: "50",
      target: "66",
      value: 40,
      description: "Group 2 Star",
      group: 2,
    },

    // Additional connections within Group 2 - Small circles
    {
      source: "34",
      target: "35",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "35",
      target: "36",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "36",
      target: "34",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },

    {
      source: "40",
      target: "41",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "41",
      target: "42",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "42",
      target: "40",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },

    {
      source: "55",
      target: "56",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "56",
      target: "57",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "57",
      target: "55",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },

    {
      source: "63",
      target: "64",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "64",
      target: "65",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },
    {
      source: "65",
      target: "63",
      value: 25,
      description: "Group 2 Circle",
      group: 2,
    },

    // GROUP 3 LINKS - Tree structure for Group 3 with node 83 as root
    {
      source: "83",
      target: "67",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "83",
      target: "73",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "83",
      target: "93",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "67",
      target: "68",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "67",
      target: "69",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "67",
      target: "70",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "73",
      target: "74",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "73",
      target: "75",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "73",
      target: "76",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "93",
      target: "94",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "93",
      target: "95",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "93",
      target: "96",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "68",
      target: "71",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "68",
      target: "72",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "69",
      target: "77",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "69",
      target: "78",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "70",
      target: "79",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "70",
      target: "80",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "74",
      target: "81",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "74",
      target: "82",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "76",
      target: "84",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "76",
      target: "85",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "94",
      target: "86",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "94",
      target: "87",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "95",
      target: "88",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "95",
      target: "89",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    {
      source: "96",
      target: "90",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "96",
      target: "91",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },
    {
      source: "96",
      target: "92",
      value: 50,
      description: "Group 3 Tree",
      group: 3,
    },

    // Additional connections within Group 3 (Chain from remaining nodes to 100)
    {
      source: "97",
      target: "98",
      value: 50,
      description: "Group 3 Chain",
      group: 3,
    },
    {
      source: "98",
      target: "99",
      value: 50,
      description: "Group 3 Chain",
      group: 3,
    },
    {
      source: "99",
      target: "100",
      value: 50,
      description: "Group 3 Chain",
      group: 3,
    },
    {
      source: "100",
      target: "83",
      value: 50,
      description: "Group 3 Chain",
      group: 3,
    },
  ],
};
export const colos = [
  "#f87171", // red-400 (department)
  "#fb923c", // orange-400 (fruit)
  "#fbbf24", // amber-400 (3c)
  "#facc15", // yellow-400 (sports)
  "#a3e635", // lime-400 (windows)
  "#4ade80", // green-400 (apple)
  "#2dd4bf", // teal-400 (coffee)
  "#22d3ee", // cyan-400 (orange)
  "#60a5fa", // blue-400 (banana)
  "#818cf8", // indigo-400 (default)
  "#a78bfa", // violet-400
  "#c084fc", // purple-400
  "#e879f9", // fuchsia-400
  "#f472b6", // pink-400
  "#94a3b8", // slate-400
];
